package com.yyw.community.mycommunity.entity;

public class Carousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.title
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.url
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.image
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.type
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.status
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_carousel.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.id
     *
     * @return the value of t_carousel.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.id
     *
     * @param id the value for t_carousel.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.title
     *
     * @return the value of t_carousel.title
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.title
     *
     * @param title the value for t_carousel.title
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.url
     *
     * @return the value of t_carousel.url
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.url
     *
     * @param url the value for t_carousel.url
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.image
     *
     * @return the value of t_carousel.image
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.image
     *
     * @param image the value for t_carousel.image
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.type
     *
     * @return the value of t_carousel.type
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.type
     *
     * @param type the value for t_carousel.type
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.status
     *
     * @return the value of t_carousel.status
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.status
     *
     * @param status the value for t_carousel.status
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.gmt_create
     *
     * @return the value of t_carousel.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.gmt_create
     *
     * @param gmtCreate the value for t_carousel.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_carousel.gmt_modified
     *
     * @return the value of t_carousel.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_carousel.gmt_modified
     *
     * @param gmtModified the value for t_carousel.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}