package com.yyw.community.mycommunity.entity;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.parent_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.type
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentator
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.likes_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long likesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.parent_id
     *
     * @return the value of t_comment.parent_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.parent_id
     *
     * @param parentId the value for t_comment.parent_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.type
     *
     * @return the value of t_comment.type
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.type
     *
     * @param type the value for t_comment.type
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentator
     *
     * @return the value of t_comment.commentator
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentator
     *
     * @param commentator the value for t_comment.commentator
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.likes_count
     *
     * @return the value of t_comment.likes_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getLikesCount() {
        return likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.likes_count
     *
     * @param likesCount the value for t_comment.likes_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setLikesCount(Long likesCount) {
        this.likesCount = likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_count
     *
     * @return the value of t_comment.comment_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_count
     *
     * @param commentCount the value for t_comment.comment_count
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.gmt_create
     *
     * @return the value of t_comment.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.gmt_create
     *
     * @param gmtCreate the value for t_comment.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.gmt_modified
     *
     * @return the value of t_comment.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.gmt_modified
     *
     * @param gmtModified the value for t_comment.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}