package com.yyw.community.mycommunity.entity;

public class Favor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favor.id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favor.user_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favor.post_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favor.gmt_create
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favor.id
     *
     * @return the value of t_favor.id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favor.id
     *
     * @param id the value for t_favor.id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favor.user_id
     *
     * @return the value of t_favor.user_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favor.user_id
     *
     * @param userId the value for t_favor.user_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favor.post_id
     *
     * @return the value of t_favor.post_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favor.post_id
     *
     * @param postId the value for t_favor.post_id
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favor.gmt_create
     *
     * @return the value of t_favor.gmt_create
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favor.gmt_create
     *
     * @param gmtCreate the value for t_favor.gmt_create
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}