package com.yyw.community.mycommunity.entity;

public class Likes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.user_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.comment_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.gmt_created
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    private Long gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.gmt_modified
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.id
     *
     * @return the value of likes.id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.id
     *
     * @param id the value for likes.id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.user_id
     *
     * @return the value of likes.user_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.user_id
     *
     * @param userId the value for likes.user_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.comment_id
     *
     * @return the value of likes.comment_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.comment_id
     *
     * @param commentId the value for likes.comment_id
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.gmt_created
     *
     * @return the value of likes.gmt_created
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public Long getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.gmt_created
     *
     * @param gmtCreated the value for likes.gmt_created
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public void setGmtCreated(Long gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.gmt_modified
     *
     * @return the value of likes.gmt_modified
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.gmt_modified
     *
     * @param gmtModified the value for likes.gmt_modified
     *
     * @mbg.generated Fri Sep 02 11:36:27 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}