package com.yyw.community.mycommunity.entity;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long reportUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.report_post_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long reportPostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.reason
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.status
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.id
     *
     * @return the value of t_report.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.id
     *
     * @param id the value for t_report.id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_user_id
     *
     * @return the value of t_report.report_user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getReportUserId() {
        return reportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_user_id
     *
     * @param reportUserId the value for t_report.report_user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setReportUserId(Long reportUserId) {
        this.reportUserId = reportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.report_post_id
     *
     * @return the value of t_report.report_post_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getReportPostId() {
        return reportPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.report_post_id
     *
     * @param reportPostId the value for t_report.report_post_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setReportPostId(Long reportPostId) {
        this.reportPostId = reportPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.reason
     *
     * @return the value of t_report.reason
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.reason
     *
     * @param reason the value for t_report.reason
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.user_id
     *
     * @return the value of t_report.user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.user_id
     *
     * @param userId the value for t_report.user_id
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.status
     *
     * @return the value of t_report.status
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.status
     *
     * @param status the value for t_report.status
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.gmt_create
     *
     * @return the value of t_report.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.gmt_create
     *
     * @param gmtCreate the value for t_report.gmt_create
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report.gmt_modified
     *
     * @return the value of t_report.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report.gmt_modified
     *
     * @param gmtModified the value for t_report.gmt_modified
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}