package com.yyw.community.mycommunity.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.nickname
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.birthday
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.sex
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.city
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.blog
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String blog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.introduction
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.school
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.major
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.college
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.classroom
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String classroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.company
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.job
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.nickname
     *
     * @return the value of t_user_info.nickname
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.nickname
     *
     * @param nickname the value for t_user_info.nickname
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.birthday
     *
     * @return the value of t_user_info.birthday
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.birthday
     *
     * @param birthday the value for t_user_info.birthday
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sex
     *
     * @return the value of t_user_info.sex
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sex
     *
     * @param sex the value for t_user_info.sex
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.city
     *
     * @return the value of t_user_info.city
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.city
     *
     * @param city the value for t_user_info.city
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.blog
     *
     * @return the value of t_user_info.blog
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.blog
     *
     * @param blog the value for t_user_info.blog
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.introduction
     *
     * @return the value of t_user_info.introduction
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.introduction
     *
     * @param introduction the value for t_user_info.introduction
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.school
     *
     * @return the value of t_user_info.school
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.school
     *
     * @param school the value for t_user_info.school
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.major
     *
     * @return the value of t_user_info.major
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.major
     *
     * @param major the value for t_user_info.major
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.college
     *
     * @return the value of t_user_info.college
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.college
     *
     * @param college the value for t_user_info.college
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.classroom
     *
     * @return the value of t_user_info.classroom
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.classroom
     *
     * @param classroom the value for t_user_info.classroom
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.company
     *
     * @return the value of t_user_info.company
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.company
     *
     * @param company the value for t_user_info.company
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.job
     *
     * @return the value of t_user_info.job
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.job
     *
     * @param job the value for t_user_info.job
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.gmt_create
     *
     * @return the value of t_user_info.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.gmt_create
     *
     * @param gmtCreate the value for t_user_info.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.gmt_modified
     *
     * @return the value of t_user_info.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.gmt_modified
     *
     * @param gmtModified the value for t_user_info.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}