package com.yyw.community.mycommunity.entity;

public class UserHobby {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_hobby.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_hobby.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_hobby.hobby_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long hobbyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_hobby.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_hobby.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_hobby.id
     *
     * @return the value of t_user_hobby.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_hobby.id
     *
     * @param id the value for t_user_hobby.id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_hobby.user_id
     *
     * @return the value of t_user_hobby.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_hobby.user_id
     *
     * @param userId the value for t_user_hobby.user_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_hobby.hobby_id
     *
     * @return the value of t_user_hobby.hobby_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getHobbyId() {
        return hobbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_hobby.hobby_id
     *
     * @param hobbyId the value for t_user_hobby.hobby_id
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setHobbyId(Long hobbyId) {
        this.hobbyId = hobbyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_hobby.gmt_create
     *
     * @return the value of t_user_hobby.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_hobby.gmt_create
     *
     * @param gmtCreate the value for t_user_hobby.gmt_create
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_hobby.gmt_modified
     *
     * @return the value of t_user_hobby.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_hobby.gmt_modified
     *
     * @param gmtModified the value for t_user_hobby.gmt_modified
     *
     * @mbg.generated Wed Nov 09 01:52:56 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}