package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.Carousel;
import com.yyw.community.mycommunity.entity.CarouselExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    long countByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int deleteByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int insert(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int insertSelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    List<Carousel> selectByExampleWithRowbounds(CarouselExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    List<Carousel> selectByExample(CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    Carousel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByExample(@Param("record") Carousel record, @Param("example") CarouselExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByPrimaryKeySelective(Carousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_carousel
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByPrimaryKey(Carousel record);
}