package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.Favor;
import com.yyw.community.mycommunity.entity.FavorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FavorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    long countByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int deleteByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int insert(Favor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int insertSelective(Favor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    List<Favor> selectByExampleWithRowbounds(FavorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    List<Favor> selectByExample(FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    Favor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") Favor record, @Param("example") FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByExample(@Param("record") Favor record, @Param("example") FavorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByPrimaryKeySelective(Favor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_favor
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByPrimaryKey(Favor record);
}