package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.HobbyCache;
import com.yyw.community.mycommunity.entity.HobbyCacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HobbyCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    long countByExample(HobbyCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int deleteByExample(HobbyCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int insert(HobbyCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int insertSelective(HobbyCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    List<HobbyCache> selectByExampleWithRowbounds(HobbyCacheExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    List<HobbyCache> selectByExample(HobbyCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    HobbyCache selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") HobbyCache record, @Param("example") HobbyCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByExample(@Param("record") HobbyCache record, @Param("example") HobbyCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByPrimaryKeySelective(HobbyCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hobby_cache
     *
     * @mbg.generated Mon Nov 07 01:03:49 CST 2022
     */
    int updateByPrimaryKey(HobbyCache record);
}