package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.Likes;
import com.yyw.community.mycommunity.entity.LikesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    long countByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int deleteByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int insert(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int insertSelective(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    List<Likes> selectByExampleWithRowbounds(LikesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    List<Likes> selectByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    Likes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") Likes record, @Param("example") LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByExample(@Param("record") Likes record, @Param("example") LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByPrimaryKeySelective(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_likes
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByPrimaryKey(Likes record);
}