package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.Report;
import com.yyw.community.mycommunity.entity.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    long countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    List<Report> selectByExampleWithRowbounds(ReportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    Report selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbg.generated Mon Nov 07 13:39:31 CST 2022
     */
    int updateByPrimaryKey(Report record);
}