package com.yyw.community.mycommunity.mapper;

import com.yyw.community.mycommunity.entity.UserHobby;
import com.yyw.community.mycommunity.entity.UserHobbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserHobbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    long countByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int deleteByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int insert(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int insertSelective(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    List<UserHobby> selectByExampleWithRowbounds(UserHobbyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    List<UserHobby> selectByExample(UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    UserHobby selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserHobby record, @Param("example") UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByExample(@Param("record") UserHobby record, @Param("example") UserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByPrimaryKeySelective(UserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_hobby
     *
     * @mbg.generated Mon Nov 07 16:24:55 CST 2022
     */
    int updateByPrimaryKey(UserHobby record);
}